# Generated by Django 3.2.8 on 2021-11-26 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BmiMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='height')),
                ('weight', models.FloatField(verbose_name='weight')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='bmi')),
                ('result', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'underweight'), (2, 'normal'), (3, 'overweight'), (4, 'obese')], verbose_name='result')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'bmi',
                'verbose_name_plural': 'bmis',
                'db_table': 'bmimeasurement',
            },
        ),
    ]
